<?php
/**
 * ActionTimeFilter.php
 * @author liuchg
 */

namespace app\controllers;

use yii\base\ActionFilter;

class ActionTimeFilter extends ActionFilter
{
    private $_startTime;
    public $rules;
    /**
     * @var string
     */
    public $callback;
    public function beforeAction($action)
    {
        $queue = new \SplQueue();
        $string = new \SplString("xxx");

        $this->_startTime = microtime(true);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        $time = microtime(true) - $this->_startTime;
        \Yii::debug("Action '{$action->uniqueId}' spent $time second.");
        return parent::afterAction($action, $result);
    }
}
