<?php
/**
 * UserBehavior.php
 * @author liuchg
 */

namespace app\behavior;


use yii\base\ActionEvent;
use yii\base\Behavior;
use yii\base\Event;

class UserBehavior extends Behavior
{
    public $name;
    public $age;
    public $phone;
    const SENDEMAIL = 'sendEmail';
    const AFTERSEND = 'afterSend';
    public function attach($owner)
    {
        $this->owner = $owner;
        $owner->on(static::SENDEMAIL,[$this,'sendEmail']);
       // parent::attach($owner); // TODO: Change the autogenerated stub
    }

    function beforeAction(){

    }
    public function getPhone() {
        // 获取中间四位
        $middle = substr($this->phone, 3,4);
        return str_replace($middle, '****', $this->phone);
    }

    public function sendEmail(ActionEvent $event){
        $this->owner->on(static::AFTERSEND, [$this, 'afterSend'], null, false);
        var_dump('发送成功开始');
    }

    public function afterSend() {
       var_dump('发送结束');
    }
}
