<?php
/**
 * @author: liuchg
 *
 */

namespace common\models\elasticsearch;

use yii\elasticsearch\ActiveRecord;

class VinCar extends ActiveRecord
{
    public function attributes()
    {
        return ["id", "vin", "brand_name", "maker_name", "series_name", "series_level", "type_name", "chassis_type", "model_year", "displacement", "engine_type", "vehicle_type", "model", "wheelbase", "guide_price", "productive_year", "drive_mode", "gearbox_type", "gearbox_description", "gear_number", "emission_standard", "max_power", "seat_number", "tire_specification", "engine_number", "engine_parameter", "fuel_type", "body_mode", "color", "max_speed", "category", "rated_payload", "leaf_spring_sheet_num", "track_rear", "front_gauge", "tire_num", "configuring_serial_number", "cylinder_volume", "production_place", "using_nature", "outer_profile_long", "outer_profile_wide", "outer_profile_high", "cargo_compartments_inside_long", "cargo_compartments_inside_wide", "cargo_compartments_inside_high", "dricab_permitted_passenger_num", "fuel_consumption", "payload_usage_factor", "curb_weight", "axle_load", "steering_shaft_num", "steering_mode", "quasi_trailer_quality", "total_quality", "semi_trailer_saddle_max_total_quality", "chassis_manufacturer", "engine_manufacturer", "note", "sale_name", "shaft_num", "quasi_traction_total_quality", "external_model_number", "announcement_batch", "domestic_joint_import", "source_file", "source_related_number"];
    }

    /**
     * es7 版本type指定为_doc
     * @return string
     */
    public static function type()
    {
        return '_doc';
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public static function index()
    {
        return 'vin_car';
    }

    public static function getDb()
    {
        return \Yii::$app->get('elasticsearch');
    }
}
